channels:
  - microsoft
  - conda-forge

package:
  name: "{{ package }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG') | replace('v', '') }}"

source:
  path: .

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed ./{{ package }}

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - microsoft::playwright >=1.37.0
    - pytest >=6.2.4,<9.0.0
    - pytest-base-url >=1.0.0,<3.0.0
    - python-slugify >=6.0.0,<9.0.0
    {% if package == 'pytest-playwright-asyncio' %}
    - pytest-asyncio >=0.24.0
    {% endif %}

test:
  imports:
    - "{{ package | replace('-', '_') }}"
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/playwright-pytest
  summary: A pytest wrapper with {% if package == 'pytest-playwright-asyncio' %} async{% endif %}fixtures for Playwright to automate web browsers
  license: Apache-2.0
  license_file: LICENSE
